---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
      deployment.kubernetes.io/revision: "1"
  name: citus-application-gateway
  namespace: default
spec:
  replicas: 1
  selector:
      matchLabels:
        app: citus-application-gateway
        version: "kubernetes"
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
  template:
    metadata:
      name: citus-application-gateway
      labels:        
        app: citus-application-gateway
        version: "kubernetes"    
    spec:
      containers:
      - name: citus-application-gateway
        image: cuongdd1/citus-application-gateway:kubernetes
        imagePullPolicy: IfNotPresent        
        securityContext:
          privileged: false        
        ports:
        - containerPort: 8000
        - containerPort: 8001
        env: 
        - name: KONG_DATABASE
          value: cassandra
        - name: KONG_CASSANDRA_CONTACT_POINTS
          value: cassandra-database
        - name: KONG_PG_HOST
          value: cassandra-database
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:  
  labels:
    app: citus-application-gateway
  name: citus-application-gateway
  namespace: default
spec:  
  ports:
  - name: tcp-8000-8000-api    
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32000
  - name: tcp-8001-8001-admin
    port: 8001
    protocol: TCP
    targetPort: 8001
    nodePort: 32001
  selector:
    app: citus-application-gateway
  type: NodePort
---
