kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: userdata-pvc
  labels:
    type: amazonEBS
  namespace: cuongdd1-fsoftcomvn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi