#!/bin/sh

export CITUS_CASSANDRA_REST=http://192.168.99.100:8020/api/v1/proxy/namespaces/default/services/citus-cassandra-rest:80
export CITUS_APPLICATION_GATEWAY=http://192.168.99.100:8020/api/v1/proxy/namespaces/default/services/citus-application-gateway:8001

curl "${CITUS_CASSANDRA_REST}/browser/citus" -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"keyspace_name":"citus","replication":{"class":"SimpleStrategy","replication_factor":1}}' --compressed
curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"keyspace":"","query":" create table citus.apps (\n\tid uuid,\n\tname varchar,\n\timage varchar,\n\ttype varchar,\n\townerid ascii,\n\tauthor text,\n\tlinks list<varchar>,\n\tservice varchar,\n\tstatus ascii,\n\tdescription text,\n\tcolor varchar,\n\tenv varchar,\n\ttarget varchar,\t\n\tcreated bigint,\n\tmodified bigint,\n\tPRIMARY KEY (id, ownerid)\n\t);"}' --compressed
curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"keyspace":"","query":"CREATE INDEX ON citus.apps (status);"}' --compressed
curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"keyspace":"","query":"CREATE INDEX ON citus.apps (links);"}' --compressed
curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"keyspace":"","query":"create table citus.types (\n\tid uuid primary key,\n\tname varchar,\n\tvalue varchar\n\t); "}' --compressed
curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"keyspace":"","query":"create table citus.users (\t\n\tid varchar primary key,\n\tname varchar,\n\temail varchar,\n\tgiven_name varchar,\n\tfamily_name varchar,\t\n\tpicture varchar,\n\tsubscription_type varchar,\n\tstatus ascii\n\t);"}' --compressed
curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"keyspace":"","query":"CREATE INDEX ON citus.users (subscription_type);"}' --compressed
curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"keyspace":"","query":"CREATE INDEX ON citus.users (status);"}' --compressed

curl "${CITUS_APPLICATION_GATEWAY}/apis/" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"name": "citus-cassandra-rest","request_path": "\/citus-cassandra-rest","upstream_url": "http:\/\/citus-cassandra-rest.default.svc.cluster.local\/","strip_request_path": true,"preserve_host": false}' --compressed
curl "${CITUS_APPLICATION_GATEWAY}/apis/" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"name": "device-management-service","request_path": "\/device-management-service","upstream_url": "http:\/\/device-management-service.default.svc.cluster.local\/","strip_request_path": true,"preserve_host": false}' --compressed
curl "${CITUS_APPLICATION_GATEWAY}/apis/" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"name": "device-management-service-docs","request_path": "\/device-management-service-docs","upstream_url": "http:\/\/device-management-service.default.svc.cluster.local\/docs","strip_request_path": true,"preserve_host": false}' --compressed

curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"keyspace":"","query":" insert into citus.apps (id, name, image, type, ownerid, author, service, status, description, color, env, target, created) values (uuid(), \'Sensor Dashboard\', \'cuongdd1/sensor-remote-dashboard\', \'dashboard\', \'auth0|system-default-account\', \'system\', \'sensor-dashboard\', \'approved\', \'A Sensor Remote Dashboard application that allows you monitoring your sensor data over device network.\', \'yellow\', \'AUTH0_CLIENT_SECRET=Auth0ClientSecret,AWS_ACCESS_KEY_ID=AWSIoTThingShadowID,AWS_SECRET_ACCESS_KEY=AWSIoTThingShadowKey,AWS_DEFAULT_REGION=ap-northeast-1,ELASTIC_SEARCH_SERVICE=http://citus-elasticsearch-svc.default.svc.cluster.local/telemetry/sensors/_search,DEVICE_LIFECYCLE_SERVICE=http://v1.apps.citus.io/apisrv/device-lifecycle-service\', \'1880/TCP\' , 1487047059582)"}' --compressed
curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"keyspace":"","query":"insert into citus.apps (id, name, image, type, ownerid, author, service, status, description, color, env, target, created) values (uuid(), \'Seniot Gateway\', \'cuongdd1/seniot-gateway\', \'gateway\', \'auth0|system-default-account\', \'system\', \'seniot-gateway\', \'approved\', \'A Device Gateway that allows you managing secure communication between IoT Device and Cloud Services.\', \'gray\', \'AWS_ACCESS_KEY_ID=AWSIoTThingShadowID,AWS_SECRET_ACCESS_KEY=AWSIoTThingShadowKey,AWS_DEFAULT_REGION=ap-northeast-1\', \'1880/TCP\' , 1487047453973)"}' --compressed
curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"keyspace":"","query":"insert into citus.apps (id, name, image, type, ownerid, author, service, status, description, color, env, target, created) values (uuid(), \'Sensor Analytics\', \'cuongdd1/citus-sensor-analytics\', \'analytics\', \'auth0|system-default-account\', \'system\', \'seniot-analytics\', \'published\', \'A Sensor Analytics application that allows you discovering your sensor data over devices.\', \'gray\', \'ELASTIC_SEARCH_SERVICE=http://citus-elasticsearch-svc.default.svc.cluster.local/telemetry/sensors/_search,DEVICE_LIFECYCLE_SERVICE=http://device-lifecycle-service.default.svc.cluster.local\', \'1880/TCP\' , 1487047170101)"}' --compressed
curl "${CITUS_CASSANDRA_REST}/query" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"keyspace":"","query":"insert into citus.apps (id, name, image, type, ownerid, author, service, status, description, color, env, target, created) values (uuid(), \'Recognition Toolkit\', \'cuongdd1/citus-recognition-service\', \'analytics\', \'auth0|system-default-account\', \'system\', \'seniot-analytics\', \'published\', \'A set of Citus Recognition Services that allow to detect your face or your car plate number.\', \'gray\', \'AWS_ACCESS_KEY_ID=AWSIoTThingShadowID,AWS_SECRET_ACCESS_KEY=AWSIoTThingShadowKey,AWS_DEFAULT_REGION=ap-northeast-1,API_KEY=,SECRET_KEY=,\', \'3000/TCP\' , 1492418866126)"}' --compressed

curl "${CITUS_APPLICATION_GATEWAY}/apis/" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"name": "sensor-analytics-website","request_path": "\/sensor-analytics~auth0-system-default-account","upstream_url": "http:\/\/sensor-analytics.default.svc.cluster.local\/","strip_request_path": true,"preserve_host": false}' --compressed
curl "${CITUS_APPLICATION_GATEWAY}/apis/" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"name": "sensor-analytics-service","request_path": "\/sensor-analytics-service","upstream_url": "http:\/\/sensor-analytics.default.svc.cluster.local\/","strip_request_path": true,"preserve_host": false}' --compressed
curl "${CITUS_APPLICATION_GATEWAY}/apis/" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"name": "sensor-analytics-docs","request_path": "\/sensor-analytics/docs","upstream_url": "http:\/\/sensor-analytics.default.svc.cluster.local\/docs","strip_request_path": true,"preserve_host": false}' --compressed
curl "${CITUS_APPLICATION_GATEWAY}/apis/" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"name": "recognition-toolkit-website","request_path": "\/recognition-toolkit~auth0-system-default-account","upstream_url": "http:\/\/recognition-toolkit.default.svc.cluster.local\/","strip_request_path": true,"preserve_host": false}' --compressed
curl "${CITUS_APPLICATION_GATEWAY}/apis/" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"name": "recognition-toolkit-docs","request_path": "\/recognition-toolkit/docs","upstream_url": "http:\/\/recognition-toolkit.default.svc.cluster.local\/docs","strip_request_path": true,"preserve_host": false}' --compressed
curl "${CITUS_APPLICATION_GATEWAY}/apis/" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"name": "recognition-toolkit-plate","request_path": "\/plate-recognition","upstream_url": "http:\/\/recognition-toolkit.default.svc.cluster.local\/plate-recognition","strip_request_path": true,"preserve_host": false}' --compressed
curl "${CITUS_APPLICATION_GATEWAY}/apis/" -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"name": "recognition-toolkit-face","request_path": "\/face-detection","upstream_url": "http:\/\/recognition-toolkit.default.svc.cluster.local\/face-detection","strip_request_path": true,"preserve_host": false}' --compressed

