kind: PersistentVolume
apiVersion: v1
metadata:
  name: cassandra-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-01275c060afeb88fd
    fsType: ext4
