kind: PersistentVolume
apiVersion: v1
metadata:
  name: userdata-pv-010
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-07ea224e0ed0b75a4
    fsType: ext4
