kind: PersistentVolume
apiVersion: v1
metadata:
  name: userdata-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-03b84e878cce5c701
    fsType: ext4
